{% set name = "tkdialog-wrapper" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tkdialog-wrapper-{{ version }}.tar.gz
  sha256: e1b00531e9f6654466c0309075437adb8c29a92109e1b87338df8cf507797bb3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.4
    - pip
  run:
    - python >=3.4

test:
  imports:
    - tkdialog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/KosukeMizuno/tkdialog
  summary: A wrapper library to use tkinter dialogs easily.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - KosukeMizuno
